Update according to comment on AUR Web
S7evinK/conduit-archlinux pull request #1
Opened 2021-09-03 09:20 UTC by S7evinK

2022-02-12 04:26 UTC, chris-morgan commented
OK, I finally got back to this (funny how time flies).

- The conduit-example.toml patch needs to be modified: there’s a new line `database_backend = "rocksdb"` immediately below the `database_path` line.

- Having thought more about it, I prefer /etc/matrix-conduit/conduit.toml to /etc/matrix-conduit.toml: that way if more /etc files get added later, no change is required. Not a big deal by any means.

- I’m in favour of renaming the package from matrix-conduit to conduit. The word “matrix” in the name is basically noise; if there were already a package named conduit I could understand it, but when there isn’t I don’t think it’s necessary.

- I have now successfully built and installed it, and it’s running. Most functionality doesn’t seem to be working, but I’ll file issues on Conduit about that because I believe the problems are with it rather than with this package.

2022-02-26 09:07 UTC, S7evinK commented
Thanks for the feedback (again), and sorry for my delay. 
I've talked to Conduits maintainer and he'd like to keep the word "matrix" in the package name.

Just pushed a small update, if you'd like to verify that the package is OK now. :)

2022-04-02 10:21 UTC, Xiretza requested changes
See the [Rust package guidelines](https://wiki.archlinux.org/title/Rust_package_guidelines). `--all-features` had to be removed from the cargo invocations because the conduit repo contains broken code gated by some non-default features (`heed` and `sled` at time of writing).

2022-04-02 10:21 UTC, Xiretza commented on PKGBUILD
> +  patch --forward --strip=1 --input="${srcdir}/0002-example-info.patch"
```
  cargo fetch --locked --target "$CARCH-unknown-linux-gnu"
```

2022-04-02 10:21 UTC, Xiretza commented on PKGBUILD
> +  env CARGO_INCREMENTAL=0 cargo build --release --locked
```suggestion
  export RUSTUP_TOOLCHAIN=stable
  export CARGO_TARGET_DIR=target
  cargo build --frozen --release
```

2022-04-02 10:21 UTC, Xiretza commented on PKGBUILD
```
check() {
  cd "$_pkgname"

  export RUSTUP_TOOLCHAIN=stable
  cargo test --frozen
}
```

2022-04-16 14:14 UTC, merged